# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\GIT\yorick_biped2bone/uidef/Biped2Bone.ui'
#
# Created: Mon Oct  9 01:46:24 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(544, 695)
        MainWindow.setWindowTitle("Biped 2 Bone Converter")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(2000, 2000))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.b_Reload = QtWidgets.QPushButton(self.centralwidget)
        self.b_Reload.setMinimumSize(QtCore.QSize(102, 32))
        self.b_Reload.setMaximumSize(QtCore.QSize(102, 32))
        self.b_Reload.setAutoFillBackground(True)
        self.b_Reload.setIconSize(QtCore.QSize(32, 32))
        self.b_Reload.setDefault(False)
        self.b_Reload.setFlat(True)
        self.b_Reload.setObjectName("b_Reload")
        self.horizontalLayout_2.addWidget(self.b_Reload)
        self.b_Unload = QtWidgets.QPushButton(self.centralwidget)
        self.b_Unload.setMinimumSize(QtCore.QSize(102, 32))
        self.b_Unload.setMaximumSize(QtCore.QSize(102, 32))
        self.b_Unload.setAutoFillBackground(True)
        self.b_Unload.setIconSize(QtCore.QSize(32, 32))
        self.b_Unload.setDefault(False)
        self.b_Unload.setFlat(True)
        self.b_Unload.setObjectName("b_Unload")
        self.horizontalLayout_2.addWidget(self.b_Unload)
        self.b_Expand = QtWidgets.QPushButton(self.centralwidget)
        self.b_Expand.setMinimumSize(QtCore.QSize(102, 32))
        self.b_Expand.setMaximumSize(QtCore.QSize(102, 32))
        self.b_Expand.setAutoFillBackground(True)
        self.b_Expand.setIconSize(QtCore.QSize(32, 32))
        self.b_Expand.setFlat(True)
        self.b_Expand.setObjectName("b_Expand")
        self.horizontalLayout_2.addWidget(self.b_Expand)
        self.b_Collapse = QtWidgets.QPushButton(self.centralwidget)
        self.b_Collapse.setMinimumSize(QtCore.QSize(102, 32))
        self.b_Collapse.setMaximumSize(QtCore.QSize(102, 32))
        self.b_Collapse.setAutoFillBackground(True)
        self.b_Collapse.setIconSize(QtCore.QSize(32, 32))
        self.b_Collapse.setFlat(True)
        self.b_Collapse.setObjectName("b_Collapse")
        self.horizontalLayout_2.addWidget(self.b_Collapse)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.le_rename_from = QtWidgets.QLineEdit(self.groupBox)
        self.le_rename_from.setMinimumSize(QtCore.QSize(0, 25))
        self.le_rename_from.setMaximumSize(QtCore.QSize(16777215, 25))
        self.le_rename_from.setMaxLength(64)
        self.le_rename_from.setFrame(True)
        self.le_rename_from.setAlignment(QtCore.Qt.AlignCenter)
        self.le_rename_from.setPlaceholderText("")
        self.le_rename_from.setObjectName("le_rename_from")
        self.gridLayout.addWidget(self.le_rename_from, 2, 0, 1, 1)
        self.le_rename_to = QtWidgets.QLineEdit(self.groupBox)
        self.le_rename_to.setMinimumSize(QtCore.QSize(0, 25))
        self.le_rename_to.setMaximumSize(QtCore.QSize(16777215, 25))
        self.le_rename_to.setMaxLength(64)
        self.le_rename_to.setFrame(True)
        self.le_rename_to.setAlignment(QtCore.Qt.AlignCenter)
        self.le_rename_to.setPlaceholderText("")
        self.le_rename_to.setObjectName("le_rename_to")
        self.gridLayout.addWidget(self.le_rename_to, 2, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_BipedList = QtWidgets.QTreeWidget(self.centralwidget)
        self.l_BipedList.setMinimumSize(QtCore.QSize(50, 50))
        self.l_BipedList.setAutoFillBackground(True)
        self.l_BipedList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.l_BipedList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.l_BipedList.setObjectName("l_BipedList")
        self.verticalLayout.addWidget(self.l_BipedList)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.l_BoneList = QtWidgets.QTreeWidget(self.centralwidget)
        self.l_BoneList.setMinimumSize(QtCore.QSize(50, 50))
        self.l_BoneList.setAutoFillBackground(True)
        self.l_BoneList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.l_BoneList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.l_BoneList.setObjectName("l_BoneList")
        self.verticalLayout_2.addWidget(self.l_BoneList)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b_GenBones = QtWidgets.QPushButton(self.centralwidget)
        self.b_GenBones.setMinimumSize(QtCore.QSize(0, 42))
        self.b_GenBones.setAutoFillBackground(True)
        self.b_GenBones.setFlat(True)
        self.b_GenBones.setObjectName("b_GenBones")
        self.horizontalLayout_3.addWidget(self.b_GenBones)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.b_Reload.setText(QtWidgets.QApplication.translate("MainWindow", "Reload", None, -1))
        self.b_Unload.setText(QtWidgets.QApplication.translate("MainWindow", "Unload", None, -1))
        self.b_Expand.setText(QtWidgets.QApplication.translate("MainWindow", "Expand", None, -1))
        self.b_Collapse.setText(QtWidgets.QApplication.translate("MainWindow", "Collapse", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "GroupBox", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Naming Rule", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.le_rename_from.setText(QtWidgets.QApplication.translate("MainWindow", "Bip", None, -1))
        self.le_rename_to.setText(QtWidgets.QApplication.translate("MainWindow", "Bone", None, -1))
        self.l_BipedList.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Scene Items", None, -1))
        self.l_BoneList.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "Bone", None, -1))
        self.b_GenBones.setText(QtWidgets.QApplication.translate("MainWindow", "Generate Bones", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "developed by Maverick Games", None, -1))

import res_rc
